# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by Django 1.11.4 on 2017-09-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('crisis_name', models.CharField(max_length=30)),
            ], ),
    ]
