# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('Analyst', 'Analyst'), ('Operator', 'Operator'), ('Chief', 'Chief')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PMORequest', 'Awaiting PMO Approval'), ('CORequest', 'Awaiting CO Approval'), ('Rejected', 'Rejected'), ('Planning', 'Planning'), ('PMOApproved', 'Approved')], max_length=20)),
                ('COComments', models.TextField(null=True)),
                ('PMOComments', models.TextField(null=True)),
                ('resolutionTime', models.DurationField()),
                ('projectedCasualties', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('Clean-up', 'Clean up'), ('Combat', 'Combat'), ('Resolved', 'Resolved')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Clean-up', 'Clean up'), ('Ongoing', 'Ongoing'), ('Resolved', 'Resolved')], max_length=20)),
                ('analyst', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('radius', models.IntegerField(verbose_name='Radius(Metres)')),
                ('crisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EFUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('affectedRadius', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Affected Radius')),
                ('totalInjured', models.IntegerField(verbose_name='Total Injured')),
                ('totalDeaths', models.IntegerField(verbose_name='Total Deaths')),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('actionPlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.ActionPlan')),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis')),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('currentUtilisation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForceDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actionPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.ActionPlan')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmoapp.Force')),
            ],
        ),
        migrations.CreateModel(
            name='ForceUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilization', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Force')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.EFUpdate')),
            ],
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='crisisType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmoapp.CrisisType'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis'),
        ),
    ]
