# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('Analyst', 'Analyst'), ('Operator', 'Operator'), ('Chief', 'Chief')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('COApproval', models.BooleanField()),
                ('PMOApproval', models.BooleanField()),
                ('ResolutionTime', models.DurationField()),
                ('ProjectedCasualties', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('Crisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EFUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('affectedRadius', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totalInjured', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('duration', models.DurationField()),
                ('ActionPlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.ActionPlan')),
                ('Crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis')),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForceDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ActionPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.ActionPlan')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmoapp.Force')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('radius', models.IntegerField()),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis')),
            ],
        ),
        migrations.AddField(
            model_name='crisis',
            name='crisistypes',
            field=models.ManyToManyField(to='cmoapp.CrisisType'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis'),
        ),
    ]
