# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionplan',
            old_name='projectedCasualties',
            new_name='projected_casualties',
        ),
        migrations.RenameField(
            model_name='actionplan',
            old_name='resolutionTime',
            new_name='resolution_time',
        ),
    ]
