# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efupdate',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
