# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='outgoing_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
