# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForceUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilization', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Force')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.EFUpdate')),
            ],
        ),
        migrations.RemoveField(
            model_name='forcedeployment',
            name='max',
        ),
    ]
