# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.CharField(choices=[('PMO', "Prime Minister's Office"), ('CO', 'Chief Officer')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='actionplan',
            name='COComments',
        ),
        migrations.RemoveField(
            model_name='actionplan',
            name='PMOComments',
        ),
        migrations.AddField(
            model_name='comments',
            name='actionPlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.ActionPlan'),
        ),
    ]
