# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='status',
            field=models.CharField(choices=[('PMOApproved', 'Approved'), ('PMORequest', 'Awaiting PMO Approval'), ('CORequest', 'Awaiting CO Approval'), ('Planning', 'Planning'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
