# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='external_agencies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
