# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('new', models.BooleanField(default=True)),
                ('_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Account')),
            ],
        ),
    ]
