# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('COApproval', models.BooleanField()),
                ('PMOApproval', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CrisisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EFUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('affectedRadius', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totalInjured', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('ActionPlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.ActionPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForceDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmoapp.Force')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='crisis_name',
        ),
        migrations.AddField(
            model_name='location',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis'),
        ),
        migrations.AddField(
            model_name='efupdate',
            name='Crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis'),
        ),
        migrations.AddField(
            model_name='crisistype',
            name='crisis',
            field=models.ManyToManyField(to='cmoapp.Crisis'),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='Crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.Crisis'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='analyst',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.Analyst'),
        ),
    ]
