# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='analyst',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmoapp.Account'),
        ),
    ]
