# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0002_auto_20171029_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionplan',
            old_name='planNumber',
            new_name='plan_number',
        ),
    ]
