# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
