# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0002_auto_20171101_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efupdate',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
