# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0003_auto_20171029_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='type',
            field=models.CharField(choices=[('Combat', 'Combat'), ('Clean-up', 'Clean Up'), ('Resolved', 'Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='status',
            field=models.CharField(choices=[('Clean-up', 'Clean Up'), ('Ongoing', 'Ongoing'), ('Resolved', 'Resolved')], max_length=20),
        ),
    ]
