# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0003_auto_20171101_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='efupdate',
            name='type',
            field=models.CharField(choices=[('Request', 'Request'), ('Notifications', 'Notifications')], default='Notifications', max_length=40),
            preserve_default=False,
        ),
    ]
