# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0004_efupdate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='force',
            name='currentUtilisation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forcedeployment',
            name='max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapp.CrisisReport'),
        ),
    ]
