# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0004_efupdate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efupdate',
            name='type',
            field=models.CharField(choices=[('Request', 'Request'), ('Notification', 'Notification')], max_length=40),
        ),
    ]
