# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0004_efupdate_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisis',
            options={'ordering': ['analyst']},
        ),
    ]
