# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0004_auto_20171022_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='projectedCasualties',
            field=models.IntegerField(),
        ),
    ]
