# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0005_auto_20171017_1343'),
        ('cmoapp', '0005_auto_20171017_2259'),
    ]

    operations = [
    ]
