# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0005_auto_20171023_0906'),
        ('cmoapp', '0003_auto_20171021_1550'),
    ]

    operations = [
    ]
