# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0006_merge_20171018_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisis',
            options={},
        ),
    ]
