# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0007_auto_20171018_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='crisis',
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='CrisisType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmoapp.CrisisType'),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=100, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=100, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='radius',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
