# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapp', '0008_auto_20171019_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='crisistypes',
        ),
    ]
